/* automatically generated by rust-bindgen */

#[repr(C)]
pub struct __BindgenUnionField<T>(::std::marker::PhantomData<T>);
impl<T> __BindgenUnionField<T> {
    #[inline]
    pub const fn new() -> Self {
        __BindgenUnionField(::std::marker::PhantomData)
    }
    #[inline]
    pub unsafe fn as_ref(&self) -> &T {
        ::std::mem::transmute(self)
    }
    #[inline]
    pub unsafe fn as_mut(&mut self) -> &mut T {
        ::std::mem::transmute(self)
    }
}
impl<T> ::std::default::Default for __BindgenUnionField<T> {
    #[inline]
    fn default() -> Self {
        Self::new()
    }
}
impl<T> ::std::clone::Clone for __BindgenUnionField<T> {
    #[inline]
    fn clone(&self) -> Self {
        Self::new()
    }
}
impl<T> ::std::marker::Copy for __BindgenUnionField<T> {}
impl<T> ::std::fmt::Debug for __BindgenUnionField<T> {
    fn fmt(&self, fmt: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        fmt.write_str("__BindgenUnionField")
    }
}
impl<T> ::std::hash::Hash for __BindgenUnionField<T> {
    fn hash<H: ::std::hash::Hasher>(&self, _state: &mut H) {}
}
impl<T> ::std::cmp::PartialEq for __BindgenUnionField<T> {
    fn eq(&self, _other: &__BindgenUnionField<T>) -> bool {
        true
    }
}
impl<T> ::std::cmp::Eq for __BindgenUnionField<T> {}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OptixDeviceContext_t {
    _unused: [u8; 0],
}
pub type OptixDeviceContext = *mut OptixDeviceContext_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OptixModule_t {
    _unused: [u8; 0],
}
pub type OptixModule = *mut OptixModule_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OptixProgramGroup_t {
    _unused: [u8; 0],
}
pub type OptixProgramGroup = *mut OptixProgramGroup_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OptixPipeline_t {
    _unused: [u8; 0],
}
pub type OptixPipeline = *mut OptixPipeline_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OptixDenoiser_t {
    _unused: [u8; 0],
}
pub type OptixDenoiser = *mut OptixDenoiser_t;
pub type OptixTraversableHandle = ::std::os::raw::c_ulonglong;
pub type OptixVisibilityMask = ::std::os::raw::c_uint;
#[repr(u32)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum OptixResult {
    OPTIX_SUCCESS = 0,
    OPTIX_ERROR_INVALID_VALUE = 7001,
    OPTIX_ERROR_HOST_OUT_OF_MEMORY = 7002,
    OPTIX_ERROR_INVALID_OPERATION = 7003,
    OPTIX_ERROR_FILE_IO_ERROR = 7004,
    OPTIX_ERROR_INVALID_FILE_FORMAT = 7005,
    OPTIX_ERROR_DISK_CACHE_INVALID_PATH = 7010,
    OPTIX_ERROR_DISK_CACHE_PERMISSION_ERROR = 7011,
    OPTIX_ERROR_DISK_CACHE_DATABASE_ERROR = 7012,
    OPTIX_ERROR_DISK_CACHE_INVALID_DATA = 7013,
    OPTIX_ERROR_LAUNCH_FAILURE = 7050,
    OPTIX_ERROR_INVALID_DEVICE_CONTEXT = 7051,
    OPTIX_ERROR_CUDA_NOT_INITIALIZED = 7052,
    OPTIX_ERROR_INVALID_PTX = 7200,
    OPTIX_ERROR_INVALID_LAUNCH_PARAMETER = 7201,
    OPTIX_ERROR_INVALID_PAYLOAD_ACCESS = 7202,
    OPTIX_ERROR_INVALID_ATTRIBUTE_ACCESS = 7203,
    OPTIX_ERROR_INVALID_FUNCTION_USE = 7204,
    OPTIX_ERROR_INVALID_FUNCTION_ARGUMENTS = 7205,
    OPTIX_ERROR_PIPELINE_OUT_OF_CONSTANT_MEMORY = 7250,
    OPTIX_ERROR_PIPELINE_LINK_ERROR = 7251,
    OPTIX_ERROR_INTERNAL_COMPILER_ERROR = 7299,
    OPTIX_ERROR_DENOISER_MODEL_NOT_SET = 7300,
    OPTIX_ERROR_DENOISER_NOT_INITIALIZED = 7301,
    OPTIX_ERROR_ACCEL_NOT_COMPATIBLE = 7400,
    OPTIX_ERROR_NOT_SUPPORTED = 7800,
    OPTIX_ERROR_UNSUPPORTED_ABI_VERSION = 7801,
    OPTIX_ERROR_FUNCTION_TABLE_SIZE_MISMATCH = 7802,
    OPTIX_ERROR_INVALID_ENTRY_FUNCTION_OPTIONS = 7803,
    OPTIX_ERROR_LIBRARY_NOT_FOUND = 7804,
    OPTIX_ERROR_ENTRY_SYMBOL_NOT_FOUND = 7805,
    OPTIX_ERROR_CUDA_ERROR = 7900,
    OPTIX_ERROR_INTERNAL_ERROR = 7990,
    OPTIX_ERROR_UNKNOWN = 7999,
}
pub const OptixDeviceProperty_OPTIX_DEVICE_PROPERTY_LIMIT_MAX_TRACE_DEPTH:
    OptixDeviceProperty = 8193;
pub const OptixDeviceProperty_OPTIX_DEVICE_PROPERTY_LIMIT_MAX_TRAVERSABLE_GRAPH_DEPTH : OptixDeviceProperty = 8194 ;
pub const OptixDeviceProperty_OPTIX_DEVICE_PROPERTY_LIMIT_MAX_PRIMITIVES_PER_GAS : OptixDeviceProperty = 8195 ;
pub const OptixDeviceProperty_OPTIX_DEVICE_PROPERTY_LIMIT_MAX_INSTANCES_PER_IAS : OptixDeviceProperty = 8196 ;
pub const OptixDeviceProperty_OPTIX_DEVICE_PROPERTY_RTCORE_VERSION:
    OptixDeviceProperty = 8197;
pub const OptixDeviceProperty_OPTIX_DEVICE_PROPERTY_LIMIT_MAX_INSTANCE_ID:
    OptixDeviceProperty = 8198;
pub const OptixDeviceProperty_OPTIX_DEVICE_PROPERTY_LIMIT_NUM_BITS_INSTANCE_VISIBILITY_MASK : OptixDeviceProperty = 8199 ;
pub const OptixDeviceProperty_OPTIX_DEVICE_PROPERTY_LIMIT_MAX_SBT_RECORDS_PER_GAS : OptixDeviceProperty = 8200 ;
pub const OptixDeviceProperty_OPTIX_DEVICE_PROPERTY_LIMIT_MAX_SBT_OFFSET:
    OptixDeviceProperty = 8201;
pub type OptixDeviceProperty = u32;
pub type OptixLogCallback = ::std::option::Option<
    unsafe extern "C" fn(
        level: ::std::os::raw::c_uint,
        tag: *const ::std::os::raw::c_char,
        message: *const ::std::os::raw::c_char,
        cbdata: *mut ::std::os::raw::c_void,
    ),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OptixDeviceContextOptions {
    pub logCallbackFunction: OptixLogCallback,
    pub logCallbackData: *mut ::std::os::raw::c_void,
    pub logCallbackLevel: ::std::os::raw::c_int,
}
pub const OptixHitKind_OPTIX_HIT_KIND_TRIANGLE_FRONT_FACE: OptixHitKind = 254;
pub const OptixHitKind_OPTIX_HIT_KIND_TRIANGLE_BACK_FACE: OptixHitKind = 255;
pub type OptixHitKind = u32;
#[repr(u32)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum OptixIndicesFormat {
    OPTIX_INDICES_FORMAT_UNSIGNED_SHORT3 = 8450,
    OPTIX_INDICES_FORMAT_UNSIGNED_INT3 = 8451,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum OptixVertexFormat {
    OPTIX_VERTEX_FORMAT_FLOAT3 = 8481,
    OPTIX_VERTEX_FORMAT_FLOAT2 = 8482,
    OPTIX_VERTEX_FORMAT_HALF3 = 8483,
    OPTIX_VERTEX_FORMAT_HALF2 = 8484,
    OPTIX_VERTEX_FORMAT_SNORM16_3 = 8485,
    OPTIX_VERTEX_FORMAT_SNORM16_2 = 8486,
}
#[repr(C)]
pub struct OptixBuildInputTriangleArray {
    pub vertexBuffers: *const CUdeviceptr,
    pub numVertices: ::std::os::raw::c_uint,
    pub vertexFormat: OptixVertexFormat,
    pub vertexStrideInBytes: ::std::os::raw::c_uint,
    pub indexBuffer: CUdeviceptr,
    pub numIndexTriplets: ::std::os::raw::c_uint,
    pub indexFormat: OptixIndicesFormat,
    pub indexStrideInBytes: ::std::os::raw::c_uint,
    pub preTransform: CUdeviceptr,
    pub flags: *const ::std::os::raw::c_uint,
    pub numSbtRecords: ::std::os::raw::c_uint,
    pub sbtIndexOffsetBuffer: CUdeviceptr,
    pub sbtIndexOffsetSizeInBytes: ::std::os::raw::c_uint,
    pub sbtIndexOffsetStrideInBytes: ::std::os::raw::c_uint,
    pub primitiveIndexOffset: ::std::os::raw::c_uint,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OptixAabb {
    pub minX: f32,
    pub minY: f32,
    pub minZ: f32,
    pub maxX: f32,
    pub maxY: f32,
    pub maxZ: f32,
}
#[repr(C)]
pub struct OptixBuildInputCustomPrimitiveArray {
    pub aabbBuffers: *const CUdeviceptr,
    pub numPrimitives: ::std::os::raw::c_uint,
    pub strideInBytes: ::std::os::raw::c_uint,
    pub flags: *const ::std::os::raw::c_uint,
    pub numSbtRecords: ::std::os::raw::c_uint,
    pub sbtIndexOffsetBuffer: CUdeviceptr,
    pub sbtIndexOffsetSizeInBytes: ::std::os::raw::c_uint,
    pub sbtIndexOffsetStrideInBytes: ::std::os::raw::c_uint,
    pub primitiveIndexOffset: ::std::os::raw::c_uint,
}
#[repr(C)]
pub struct OptixBuildInputInstanceArray {
    pub instances: CUdeviceptr,
    pub numInstances: ::std::os::raw::c_uint,
    pub aabbs: CUdeviceptr,
    pub numAabbs: ::std::os::raw::c_uint,
}
pub const OptixBuildInputType_OPTIX_BUILD_INPUT_TYPE_TRIANGLES:
    OptixBuildInputType = 8513;
pub const OptixBuildInputType_OPTIX_BUILD_INPUT_TYPE_CUSTOM_PRIMITIVES:
    OptixBuildInputType = 8514;
pub const OptixBuildInputType_OPTIX_BUILD_INPUT_TYPE_INSTANCES:
    OptixBuildInputType = 8515;
pub const OptixBuildInputType_OPTIX_BUILD_INPUT_TYPE_INSTANCE_POINTERS:
    OptixBuildInputType = 8516;
pub type OptixBuildInputType = u32;
#[repr(C)]
pub struct OptixBuildInput__bindgen_ty_1 {
    pub triangleArray: __BindgenUnionField<OptixBuildInputTriangleArray>,
    pub aabbArray: __BindgenUnionField<OptixBuildInputCustomPrimitiveArray>,
    pub instanceArray: __BindgenUnionField<OptixBuildInputInstanceArray>,
    pub pad: __BindgenUnionField<[::std::os::raw::c_char; 1024usize]>,
    pub bindgen_union_field: [u64; 128usize],
}
pub const OptixInstanceFlags_OPTIX_INSTANCE_FLAG_NONE: OptixInstanceFlags = 0;
pub const OptixInstanceFlags_OPTIX_INSTANCE_FLAG_DISABLE_TRIANGLE_FACE_CULLING : OptixInstanceFlags = 1 ;
pub const OptixInstanceFlags_OPTIX_INSTANCE_FLAG_FLIP_TRIANGLE_FACING:
    OptixInstanceFlags = 2;
pub const OptixInstanceFlags_OPTIX_INSTANCE_FLAG_DISABLE_ANYHIT:
    OptixInstanceFlags = 4;
pub const OptixInstanceFlags_OPTIX_INSTANCE_FLAG_ENFORCE_ANYHIT:
    OptixInstanceFlags = 8;
pub const OptixInstanceFlags_OPTIX_INSTANCE_FLAG_DISABLE_TRANSFORM:
    OptixInstanceFlags = 64;
pub type OptixInstanceFlags = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OptixInstance {
    pub transform: [f32; 12usize],
    pub instanceId: ::std::os::raw::c_uint,
    pub sbtOffset: ::std::os::raw::c_uint,
    pub visibilityMask: ::std::os::raw::c_uint,
    pub flags: ::std::os::raw::c_uint,
    pub traversableHandle: OptixTraversableHandle,
    pub pad: [::std::os::raw::c_uint; 2usize],
}
pub const OptixBuildFlags_OPTIX_BUILD_FLAG_NONE: OptixBuildFlags = 0;
pub const OptixBuildFlags_OPTIX_BUILD_FLAG_ALLOW_UPDATE: OptixBuildFlags = 1;
pub const OptixBuildFlags_OPTIX_BUILD_FLAG_ALLOW_COMPACTION: OptixBuildFlags =
    2;
pub const OptixBuildFlags_OPTIX_BUILD_FLAG_PREFER_FAST_TRACE: OptixBuildFlags =
    4;
pub const OptixBuildFlags_OPTIX_BUILD_FLAG_PREFER_FAST_BUILD: OptixBuildFlags =
    8;
pub const OptixBuildFlags_OPTIX_BUILD_FLAG_ALLOW_RANDOM_VERTEX_ACCESS:
    OptixBuildFlags = 16;
pub type OptixBuildFlags = u32;
pub const OptixBuildOperation_OPTIX_BUILD_OPERATION_BUILD: OptixBuildOperation =
    8545;
pub const OptixBuildOperation_OPTIX_BUILD_OPERATION_UPDATE:
    OptixBuildOperation = 8546;
pub type OptixBuildOperation = u32;
pub const OptixMotionFlags_OPTIX_MOTION_FLAG_NONE: OptixMotionFlags = 0;
pub const OptixMotionFlags_OPTIX_MOTION_FLAG_START_VANISH: OptixMotionFlags = 1;
pub const OptixMotionFlags_OPTIX_MOTION_FLAG_END_VANISH: OptixMotionFlags = 2;
pub type OptixMotionFlags = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OptixMotionOptions {
    pub numKeys: ::std::os::raw::c_ushort,
    pub flags: ::std::os::raw::c_ushort,
    pub timeBegin: f32,
    pub timeEnd: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OptixAccelBuildOptions {
    pub buildFlags: ::std::os::raw::c_uint,
    pub operation: OptixBuildOperation,
    pub motionOptions: OptixMotionOptions,
}
#[repr(C)]
pub struct OptixAccelBufferSizes {
    pub outputSizeInBytes: usize,
    pub tempSizeInBytes: usize,
    pub tempUpdateSizeInBytes: usize,
}
pub const OptixAccelPropertyType_OPTIX_PROPERTY_TYPE_COMPACTED_SIZE:
    OptixAccelPropertyType = 8577;
pub const OptixAccelPropertyType_OPTIX_PROPERTY_TYPE_AABBS:
    OptixAccelPropertyType = 8578;
pub type OptixAccelPropertyType = u32;
#[repr(C)]
pub struct OptixAccelEmitDesc {
    pub result: CUdeviceptr,
    pub type_: OptixAccelPropertyType,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OptixAccelRelocationInfo {
    pub info: [::std::os::raw::c_ulonglong; 4usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OptixStaticTransform {
    pub child: OptixTraversableHandle,
    pub pad: [::std::os::raw::c_uint; 2usize],
    pub transform: [f32; 12usize],
    pub invTransform: [f32; 12usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OptixMatrixMotionTransform {
    pub child: OptixTraversableHandle,
    pub motionOptions: OptixMotionOptions,
    pub pad: [::std::os::raw::c_uint; 3usize],
    pub transform: [[f32; 12usize]; 2usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OptixSRTData {
    pub sx: f32,
    pub a: f32,
    pub b: f32,
    pub pvx: f32,
    pub sy: f32,
    pub c: f32,
    pub pvy: f32,
    pub sz: f32,
    pub pvz: f32,
    pub qx: f32,
    pub qy: f32,
    pub qz: f32,
    pub qw: f32,
    pub tx: f32,
    pub ty: f32,
    pub tz: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OptixSRTMotionTransform {
    pub child: OptixTraversableHandle,
    pub motionOptions: OptixMotionOptions,
    pub pad: [::std::os::raw::c_uint; 3usize],
    pub srtData: [OptixSRTData; 2usize],
}
pub const OptixTraversableType_OPTIX_TRAVERSABLE_TYPE_STATIC_TRANSFORM:
    OptixTraversableType = 8641;
pub const OptixTraversableType_OPTIX_TRAVERSABLE_TYPE_MATRIX_MOTION_TRANSFORM : OptixTraversableType = 8642 ;
pub const OptixTraversableType_OPTIX_TRAVERSABLE_TYPE_SRT_MOTION_TRANSFORM:
    OptixTraversableType = 8643;
pub type OptixTraversableType = u32;
pub const OptixPixelFormat_OPTIX_PIXEL_FORMAT_HALF3: OptixPixelFormat = 8705;
pub const OptixPixelFormat_OPTIX_PIXEL_FORMAT_HALF4: OptixPixelFormat = 8706;
pub const OptixPixelFormat_OPTIX_PIXEL_FORMAT_FLOAT3: OptixPixelFormat = 8707;
pub const OptixPixelFormat_OPTIX_PIXEL_FORMAT_FLOAT4: OptixPixelFormat = 8708;
pub const OptixPixelFormat_OPTIX_PIXEL_FORMAT_UCHAR3: OptixPixelFormat = 8709;
pub const OptixPixelFormat_OPTIX_PIXEL_FORMAT_UCHAR4: OptixPixelFormat = 8710;
pub type OptixPixelFormat = u32;
#[repr(C)]
pub struct OptixImage2D {
    pub data: CUdeviceptr,
    pub width: ::std::os::raw::c_uint,
    pub height: ::std::os::raw::c_uint,
    pub rowStrideInBytes: ::std::os::raw::c_uint,
    pub pixelStrideInBytes: ::std::os::raw::c_uint,
    pub format: OptixPixelFormat,
}
pub const OptixDenoiserInputKind_OPTIX_DENOISER_INPUT_RGB:
    OptixDenoiserInputKind = 8961;
pub const OptixDenoiserInputKind_OPTIX_DENOISER_INPUT_RGB_ALBEDO:
    OptixDenoiserInputKind = 8962;
pub const OptixDenoiserInputKind_OPTIX_DENOISER_INPUT_RGB_ALBEDO_NORMAL:
    OptixDenoiserInputKind = 8963;
pub type OptixDenoiserInputKind = u32;
pub const OptixDenoiserModelKind_OPTIX_DENOISER_MODEL_KIND_USER:
    OptixDenoiserModelKind = 8993;
pub const OptixDenoiserModelKind_OPTIX_DENOISER_MODEL_KIND_LDR:
    OptixDenoiserModelKind = 8994;
pub const OptixDenoiserModelKind_OPTIX_DENOISER_MODEL_KIND_HDR:
    OptixDenoiserModelKind = 8995;
pub type OptixDenoiserModelKind = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OptixDenoiserOptions {
    pub inputKind: OptixDenoiserInputKind,
    pub pixelFormat: OptixPixelFormat,
}
#[repr(C)]
pub struct OptixDenoiserParams {
    pub denoiseAlpha: ::std::os::raw::c_uint,
    pub hdrIntensity: CUdeviceptr,
    pub blendFactor: f32,
}
#[repr(C)]
pub struct OptixDenoiserSizes {
    pub stateSizeInBytes: usize,
    pub minimumScratchSizeInBytes: usize,
    pub recommendedScratchSizeInBytes: usize,
    pub overlapWindowSizeInPixels: ::std::os::raw::c_uint,
}
pub const OptixRayFlags_OPTIX_RAY_FLAG_NONE: OptixRayFlags = 0;
pub const OptixRayFlags_OPTIX_RAY_FLAG_DISABLE_ANYHIT: OptixRayFlags = 1;
pub const OptixRayFlags_OPTIX_RAY_FLAG_ENFORCE_ANYHIT: OptixRayFlags = 2;
pub const OptixRayFlags_OPTIX_RAY_FLAG_TERMINATE_ON_FIRST_HIT: OptixRayFlags =
    4;
pub const OptixRayFlags_OPTIX_RAY_FLAG_DISABLE_CLOSESTHIT: OptixRayFlags = 8;
pub const OptixRayFlags_OPTIX_RAY_FLAG_CULL_BACK_FACING_TRIANGLES:
    OptixRayFlags = 16;
pub const OptixRayFlags_OPTIX_RAY_FLAG_CULL_FRONT_FACING_TRIANGLES:
    OptixRayFlags = 32;
pub const OptixRayFlags_OPTIX_RAY_FLAG_CULL_DISABLED_ANYHIT: OptixRayFlags = 64;
pub const OptixRayFlags_OPTIX_RAY_FLAG_CULL_ENFORCED_ANYHIT: OptixRayFlags =
    128;
pub type OptixRayFlags = u32;
pub const OptixTransformType_OPTIX_TRANSFORM_TYPE_NONE: OptixTransformType = 0;
pub const OptixTransformType_OPTIX_TRANSFORM_TYPE_STATIC_TRANSFORM:
    OptixTransformType = 1;
pub const OptixTransformType_OPTIX_TRANSFORM_TYPE_MATRIX_MOTION_TRANSFORM:
    OptixTransformType = 2;
pub const OptixTransformType_OPTIX_TRANSFORM_TYPE_SRT_MOTION_TRANSFORM:
    OptixTransformType = 3;
pub const OptixTransformType_OPTIX_TRANSFORM_TYPE_INSTANCE: OptixTransformType =
    4;
pub type OptixTransformType = u32;
pub mod OptixTraversableGraphFlags {
    pub type Type = u32;
    pub const OPTIX_TRAVERSABLE_GRAPH_FLAG_ALLOW_ANY: Type = 0;
    pub const OPTIX_TRAVERSABLE_GRAPH_FLAG_ALLOW_SINGLE_GAS: Type = 1;
    pub const OPTIX_TRAVERSABLE_GRAPH_FLAG_ALLOW_SINGLE_LEVEL_INSTANCING: Type =
        2;
}
pub mod OptixCompileOptimizationLevel {
    pub type Type = u32;
    pub const OPTIX_COMPILE_OPTIMIZATION_LEVEL_0: Type = 0;
    pub const OPTIX_COMPILE_OPTIMIZATION_LEVEL_1: Type = 1;
    pub const OPTIX_COMPILE_OPTIMIZATION_LEVEL_2: Type = 2;
    pub const OPTIX_COMPILE_OPTIMIZATION_LEVEL_3: Type = 3;
    pub const OPTIX_COMPILE_OPTIMIZATION_DEFAULT: Type = 3;
}
pub mod OptixCompileDebugLevel {
    pub type Type = u32;
    pub const OPTIX_COMPILE_DEBUG_LEVEL_NONE: Type = 0;
    pub const OPTIX_COMPILE_DEBUG_LEVEL_LINEINFO: Type = 1;
    pub const OPTIX_COMPILE_DEBUG_LEVEL_FULL: Type = 2;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OptixModuleCompileOptions {
    pub maxRegisterCount: ::std::os::raw::c_int,
    pub optLevel: OptixCompileOptimizationLevel::Type,
    pub debugLevel: OptixCompileDebugLevel::Type,
}
pub mod OptixProgramGroupKind {
    pub type Type = u32;
    pub const OPTIX_PROGRAM_GROUP_KIND_RAYGEN: Type = 9249;
    pub const OPTIX_PROGRAM_GROUP_KIND_MISS: Type = 9250;
    pub const OPTIX_PROGRAM_GROUP_KIND_EXCEPTION: Type = 9251;
    pub const OPTIX_PROGRAM_GROUP_KIND_HITGROUP: Type = 9252;
    pub const OPTIX_PROGRAM_GROUP_KIND_CALLABLES: Type = 9253;
}
pub const OptixProgramGroupFlags_OPTIX_PROGRAM_GROUP_FLAGS_NONE:
    OptixProgramGroupFlags = 0;
pub type OptixProgramGroupFlags = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OptixProgramGroupSingleModule {
    pub module: OptixModule,
    pub entryFunctionName: *const ::std::os::raw::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OptixProgramGroupHitgroup {
    pub moduleCH: OptixModule,
    pub entryFunctionNameCH: *const ::std::os::raw::c_char,
    pub moduleAH: OptixModule,
    pub entryFunctionNameAH: *const ::std::os::raw::c_char,
    pub moduleIS: OptixModule,
    pub entryFunctionNameIS: *const ::std::os::raw::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OptixProgramGroupCallables {
    pub moduleDC: OptixModule,
    pub entryFunctionNameDC: *const ::std::os::raw::c_char,
    pub moduleCC: OptixModule,
    pub entryFunctionNameCC: *const ::std::os::raw::c_char,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct OptixProgramGroupDesc {
    pub kind: OptixProgramGroupKind::Type,
    pub flags: ::std::os::raw::c_uint,
    pub __bindgen_anon_1: OptixProgramGroupDesc__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union OptixProgramGroupDesc__bindgen_ty_1 {
    pub raygen: OptixProgramGroupSingleModule,
    pub miss: OptixProgramGroupSingleModule,
    pub exception: OptixProgramGroupSingleModule,
    pub callables: OptixProgramGroupCallables,
    pub hitgroup: OptixProgramGroupHitgroup,
    _bindgen_union_align: [u64; 6usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OptixProgramGroupOptions {
    pub placeholder: ::std::os::raw::c_int,
}
pub const OptixExceptionCodes_OPTIX_EXCEPTION_CODE_STACK_OVERFLOW:
    OptixExceptionCodes = -1;
pub const OptixExceptionCodes_OPTIX_EXCEPTION_CODE_TRACE_DEPTH_EXCEEDED:
    OptixExceptionCodes = -2;
pub const OptixExceptionCodes_OPTIX_EXCEPTION_CODE_TRAVERSAL_DEPTH_EXCEEDED:
    OptixExceptionCodes = -3;
pub const OptixExceptionCodes_OPTIX_EXCEPTION_CODE_TRAVERSAL_INVALID_TRAVERSABLE : OptixExceptionCodes = -5 ;
pub const OptixExceptionCodes_OPTIX_EXCEPTION_CODE_TRAVERSAL_INVALID_MISS_SBT : OptixExceptionCodes = -6 ;
pub const OptixExceptionCodes_OPTIX_EXCEPTION_CODE_TRAVERSAL_INVALID_HIT_SBT:
    OptixExceptionCodes = -7;
pub type OptixExceptionCodes = i32;
pub mod OptixExceptionFlags {
    pub type Type = u32;
    pub const OPTIX_EXCEPTION_FLAG_NONE: Type = 0;
    pub const OPTIX_EXCEPTION_FLAG_STACK_OVERFLOW: Type = 1;
    pub const OPTIX_EXCEPTION_FLAG_TRACE_DEPTH: Type = 2;
    pub const OPTIX_EXCEPTION_FLAG_USER: Type = 4;
    pub const OPTIX_EXCEPTION_FLAG_DEBUG: Type = 8;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OptixPipelineCompileOptions {
    pub usesMotionBlur: ::std::os::raw::c_int,
    pub traversableGraphFlags: ::std::os::raw::c_uint,
    pub numPayloadValues: ::std::os::raw::c_int,
    pub numAttributeValues: ::std::os::raw::c_int,
    pub exceptionFlags: ::std::os::raw::c_uint,
    pub pipelineLaunchParamsVariableName: *const ::std::os::raw::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OptixPipelineLinkOptions {
    pub maxTraceDepth: ::std::os::raw::c_uint,
    pub debugLevel: OptixCompileDebugLevel::Type,
    pub overrideUsesMotionBlur: ::std::os::raw::c_int,
}
#[repr(C)]
pub struct OptixShaderBindingTable {
    pub raygenRecord: CUdeviceptr,
    pub exceptionRecord: CUdeviceptr,
    pub missRecordBase: CUdeviceptr,
    pub missRecordStrideInBytes: ::std::os::raw::c_uint,
    pub missRecordCount: ::std::os::raw::c_uint,
    pub hitgroupRecordBase: CUdeviceptr,
    pub hitgroupRecordStrideInBytes: ::std::os::raw::c_uint,
    pub hitgroupRecordCount: ::std::os::raw::c_uint,
    pub callablesRecordBase: CUdeviceptr,
    pub callablesRecordStrideInBytes: ::std::os::raw::c_uint,
    pub callablesRecordCount: ::std::os::raw::c_uint,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OptixStackSizes {
    pub cssRG: ::std::os::raw::c_uint,
    pub cssMS: ::std::os::raw::c_uint,
    pub cssCH: ::std::os::raw::c_uint,
    pub cssAH: ::std::os::raw::c_uint,
    pub cssIS: ::std::os::raw::c_uint,
    pub cssCC: ::std::os::raw::c_uint,
    pub dssDC: ::std::os::raw::c_uint,
}
pub const OptixQueryFunctionTableOptions_OPTIX_QUERY_FUNCTION_TABLE_OPTION_DUMMY : OptixQueryFunctionTableOptions = 0 ;
pub type OptixQueryFunctionTableOptions = u32;
pub type OptixQueryFunctionTable_t = ::std::option::Option<
    unsafe extern "C" fn(
        ABI_ID: ::std::os::raw::c_int,
        numOptions: ::std::os::raw::c_uint,
        arg1: *mut OptixQueryFunctionTableOptions,
        arg2: *mut *const ::std::os::raw::c_void,
        functionTable: *mut ::std::os::raw::c_void,
        sizeOfTable: usize,
    ) -> OptixResult,
>;
extern "C" {
    pub fn optixGetErrorName(
        result: OptixResult,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn optixGetErrorString(
        result: OptixResult,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn optixDeviceContextCreate(
        fromContext: CUcontext,
        options: *const OptixDeviceContextOptions,
        context: *mut OptixDeviceContext,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixDeviceContextDestroy(
        context: OptixDeviceContext,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixDeviceContextGetProperty(
        context: OptixDeviceContext,
        property: OptixDeviceProperty,
        value: *mut ::std::os::raw::c_void,
        sizeInBytes: usize,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixDeviceContextSetLogCallback(
        context: OptixDeviceContext,
        callbackFunction: OptixLogCallback,
        callbackData: *mut ::std::os::raw::c_void,
        callbackLevel: ::std::os::raw::c_uint,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixDeviceContextSetCacheEnabled(
        context: OptixDeviceContext,
        enabled: ::std::os::raw::c_int,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixDeviceContextSetCacheLocation(
        context: OptixDeviceContext,
        location: *const ::std::os::raw::c_char,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixDeviceContextSetCacheDatabaseSizes(
        context: OptixDeviceContext,
        lowWaterMark: usize,
        highWaterMark: usize,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixDeviceContextGetCacheEnabled(
        context: OptixDeviceContext,
        enabled: *mut ::std::os::raw::c_int,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixDeviceContextGetCacheLocation(
        context: OptixDeviceContext,
        location: *mut ::std::os::raw::c_char,
        locationSize: usize,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixDeviceContextGetCacheDatabaseSizes(
        context: OptixDeviceContext,
        lowWaterMark: *mut usize,
        highWaterMark: *mut usize,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixPipelineCreate(
        context: OptixDeviceContext,
        pipelineCompileOptions: *const OptixPipelineCompileOptions,
        pipelineLinkOptions: *const OptixPipelineLinkOptions,
        programGroups: *const OptixProgramGroup,
        numProgramGroups: ::std::os::raw::c_uint,
        logString: *mut ::std::os::raw::c_char,
        logStringSize: *mut usize,
        pipeline: *mut OptixPipeline,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixPipelineDestroy(pipeline: OptixPipeline) -> OptixResult;
}
extern "C" {
    pub fn optixPipelineSetStackSize(
        pipeline: OptixPipeline,
        directCallableStackSizeFromTraversal: ::std::os::raw::c_uint,
        directCallableStackSizeFromState: ::std::os::raw::c_uint,
        continuationStackSize: ::std::os::raw::c_uint,
        maxTraversableGraphDepth: ::std::os::raw::c_uint,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixModuleCreateFromPTX(
        context: OptixDeviceContext,
        moduleCompileOptions: *const OptixModuleCompileOptions,
        pipelineCompileOptions: *const OptixPipelineCompileOptions,
        PTX: *const ::std::os::raw::c_char,
        PTXsize: usize,
        logString: *mut ::std::os::raw::c_char,
        logStringSize: *mut usize,
        module: *mut OptixModule,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixModuleDestroy(module: OptixModule) -> OptixResult;
}
extern "C" {
    pub fn optixProgramGroupGetStackSize(
        programGroup: OptixProgramGroup,
        stackSizes: *mut OptixStackSizes,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixProgramGroupCreate(
        context: OptixDeviceContext,
        programDescriptions: *const OptixProgramGroupDesc,
        numProgramGroups: ::std::os::raw::c_uint,
        options: *const OptixProgramGroupOptions,
        logString: *mut ::std::os::raw::c_char,
        logStringSize: *mut usize,
        programGroups: *mut OptixProgramGroup,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixProgramGroupDestroy(
        programGroup: OptixProgramGroup,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixLaunch(
        pipeline: OptixPipeline,
        stream: CUstream,
        pipelineParams: CUdeviceptr,
        pipelineParamsSize: usize,
        sbt: *const OptixShaderBindingTable,
        width: ::std::os::raw::c_uint,
        height: ::std::os::raw::c_uint,
        depth: ::std::os::raw::c_uint,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixSbtRecordPackHeader(
        programGroup: OptixProgramGroup,
        sbtRecordHeaderHostPointer: *mut ::std::os::raw::c_void,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixAccelComputeMemoryUsage(
        context: OptixDeviceContext,
        accelOptions: *const OptixAccelBuildOptions,
        buildInputs: *const OptixBuildInput,
        numBuildInputs: ::std::os::raw::c_uint,
        bufferSizes: *mut OptixAccelBufferSizes,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixAccelBuild(
        context: OptixDeviceContext,
        stream: CUstream,
        accelOptions: *const OptixAccelBuildOptions,
        buildInputs: *const OptixBuildInput,
        numBuildInputs: ::std::os::raw::c_uint,
        tempBuffer: CUdeviceptr,
        tempBufferSizeInBytes: usize,
        outputBuffer: CUdeviceptr,
        outputBufferSizeInBytes: usize,
        outputHandle: *mut OptixTraversableHandle,
        emittedProperties: *const OptixAccelEmitDesc,
        numEmittedProperties: ::std::os::raw::c_uint,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixAccelGetRelocationInfo(
        context: OptixDeviceContext,
        handle: OptixTraversableHandle,
        info: *mut OptixAccelRelocationInfo,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixAccelCheckRelocationCompatibility(
        context: OptixDeviceContext,
        info: *const OptixAccelRelocationInfo,
        compatible: *mut ::std::os::raw::c_int,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixAccelRelocate(
        context: OptixDeviceContext,
        stream: CUstream,
        info: *const OptixAccelRelocationInfo,
        instanceTraversableHandles: CUdeviceptr,
        numInstanceTraversableHandles: usize,
        targetAccel: CUdeviceptr,
        targetAccelSizeInBytes: usize,
        targetHandle: *mut OptixTraversableHandle,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixAccelCompact(
        context: OptixDeviceContext,
        stream: CUstream,
        inputHandle: OptixTraversableHandle,
        outputBuffer: CUdeviceptr,
        outputBufferSizeInBytes: usize,
        outputHandle: *mut OptixTraversableHandle,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixConvertPointerToTraversableHandle(
        onDevice: OptixDeviceContext,
        pointer: CUdeviceptr,
        traversableType: OptixTraversableType,
        traversableHandle: *mut OptixTraversableHandle,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixDenoiserCreate(
        context: OptixDeviceContext,
        options: *const OptixDenoiserOptions,
        denoiser: *mut OptixDenoiser,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixDenoiserSetModel(
        denoiser: OptixDenoiser,
        kind: OptixDenoiserModelKind,
        data: *mut ::std::os::raw::c_void,
        sizeInBytes: usize,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixDenoiserDestroy(denoiser: OptixDenoiser) -> OptixResult;
}
extern "C" {
    pub fn optixDenoiserComputeMemoryResources(
        denoiser: OptixDenoiser,
        outputWidth: ::std::os::raw::c_uint,
        outputHeight: ::std::os::raw::c_uint,
        returnSizes: *mut OptixDenoiserSizes,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixDenoiserSetup(
        denoiser: OptixDenoiser,
        stream: CUstream,
        outputWidth: ::std::os::raw::c_uint,
        outputHeight: ::std::os::raw::c_uint,
        denoiserState: CUdeviceptr,
        denoiserStateSizeInBytes: usize,
        scratch: CUdeviceptr,
        scratchSizeInBytes: usize,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixDenoiserInvoke(
        denoiser: OptixDenoiser,
        stream: CUstream,
        params: *const OptixDenoiserParams,
        denoiserState: CUdeviceptr,
        denoiserStateSizeInBytes: usize,
        inputLayers: *const OptixImage2D,
        numInputLayers: ::std::os::raw::c_uint,
        inputOffsetX: ::std::os::raw::c_uint,
        inputOffsetY: ::std::os::raw::c_uint,
        outputLayer: *const OptixImage2D,
        scratch: CUdeviceptr,
        scratchSizeInBytes: usize,
    ) -> OptixResult;
}
extern "C" {
    pub fn optixDenoiserComputeIntensity(
        denoiser: OptixDenoiser,
        stream: CUstream,
        inputImage: *const OptixImage2D,
        outputIntensity: CUdeviceptr,
        scratch: CUdeviceptr,
        scratchSizeInBytes: usize,
    ) -> OptixResult;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OptixFunctionTable {
    pub optixGetErrorName: ::std::option::Option<
        unsafe extern "C" fn(
            result: OptixResult,
        ) -> *const ::std::os::raw::c_char,
    >,
    pub optixGetErrorString: ::std::option::Option<
        unsafe extern "C" fn(
            result: OptixResult,
        ) -> *const ::std::os::raw::c_char,
    >,
    pub optixDeviceContextCreate: ::std::option::Option<
        unsafe extern "C" fn(
            fromContext: CUcontext,
            options: *const OptixDeviceContextOptions,
            context: *mut OptixDeviceContext,
        ) -> OptixResult,
    >,
    pub optixDeviceContextDestroy: ::std::option::Option<
        unsafe extern "C" fn(context: OptixDeviceContext) -> OptixResult,
    >,
    pub optixDeviceContextGetProperty: ::std::option::Option<
        unsafe extern "C" fn(
            context: OptixDeviceContext,
            property: OptixDeviceProperty,
            value: *mut ::std::os::raw::c_void,
            sizeInBytes: usize,
        ) -> OptixResult,
    >,
    pub optixDeviceContextSetLogCallback: ::std::option::Option<
        unsafe extern "C" fn(
            context: OptixDeviceContext,
            callbackFunction: OptixLogCallback,
            callbackData: *mut ::std::os::raw::c_void,
            callbackLevel: ::std::os::raw::c_uint,
        ) -> OptixResult,
    >,
    pub optixDeviceContextSetCacheEnabled: ::std::option::Option<
        unsafe extern "C" fn(
            context: OptixDeviceContext,
            enabled: ::std::os::raw::c_int,
        ) -> OptixResult,
    >,
    pub optixDeviceContextSetCacheLocation: ::std::option::Option<
        unsafe extern "C" fn(
            context: OptixDeviceContext,
            location: *const ::std::os::raw::c_char,
        ) -> OptixResult,
    >,
    pub optixDeviceContextSetCacheDatabaseSizes: ::std::option::Option<
        unsafe extern "C" fn(
            context: OptixDeviceContext,
            lowWaterMark: usize,
            highWaterMark: usize,
        ) -> OptixResult,
    >,
    pub optixDeviceContextGetCacheEnabled: ::std::option::Option<
        unsafe extern "C" fn(
            context: OptixDeviceContext,
            enabled: *mut ::std::os::raw::c_int,
        ) -> OptixResult,
    >,
    pub optixDeviceContextGetCacheLocation: ::std::option::Option<
        unsafe extern "C" fn(
            context: OptixDeviceContext,
            location: *mut ::std::os::raw::c_char,
            locationSize: usize,
        ) -> OptixResult,
    >,
    pub optixDeviceContextGetCacheDatabaseSizes: ::std::option::Option<
        unsafe extern "C" fn(
            context: OptixDeviceContext,
            lowWaterMark: *mut usize,
            highWaterMark: *mut usize,
        ) -> OptixResult,
    >,
    pub optixModuleCreateFromPTX: ::std::option::Option<
        unsafe extern "C" fn(
            context: OptixDeviceContext,
            moduleCompileOptions: *const OptixModuleCompileOptions,
            pipelineCompileOptions: *const OptixPipelineCompileOptions,
            PTX: *const ::std::os::raw::c_char,
            PTXsize: usize,
            logString: *mut ::std::os::raw::c_char,
            logStringSize: *mut usize,
            module: *mut OptixModule,
        ) -> OptixResult,
    >,
    pub optixModuleDestroy: ::std::option::Option<
        unsafe extern "C" fn(module: OptixModule) -> OptixResult,
    >,
    pub optixProgramGroupCreate: ::std::option::Option<
        unsafe extern "C" fn(
            context: OptixDeviceContext,
            programDescriptions: *const OptixProgramGroupDesc,
            numProgramGroups: ::std::os::raw::c_uint,
            options: *const OptixProgramGroupOptions,
            logString: *mut ::std::os::raw::c_char,
            logStringSize: *mut usize,
            programGroups: *mut OptixProgramGroup,
        ) -> OptixResult,
    >,
    pub optixProgramGroupDestroy: ::std::option::Option<
        unsafe extern "C" fn(programGroup: OptixProgramGroup) -> OptixResult,
    >,
    pub optixProgramGroupGetStackSize: ::std::option::Option<
        unsafe extern "C" fn(
            programGroup: OptixProgramGroup,
            stackSizes: *mut OptixStackSizes,
        ) -> OptixResult,
    >,
    pub optixPipelineCreate: ::std::option::Option<
        unsafe extern "C" fn(
            context: OptixDeviceContext,
            pipelineCompileOptions: *const OptixPipelineCompileOptions,
            pipelineLinkOptions: *const OptixPipelineLinkOptions,
            programGroups: *const OptixProgramGroup,
            numProgramGroups: ::std::os::raw::c_uint,
            logString: *mut ::std::os::raw::c_char,
            logStringSize: *mut usize,
            pipeline: *mut OptixPipeline,
        ) -> OptixResult,
    >,
    pub optixPipelineDestroy: ::std::option::Option<
        unsafe extern "C" fn(pipeline: OptixPipeline) -> OptixResult,
    >,
    pub optixPipelineSetStackSize: ::std::option::Option<
        unsafe extern "C" fn(
            pipeline: OptixPipeline,
            directCallableStackSizeFromTraversal: ::std::os::raw::c_uint,
            directCallableStackSizeFromState: ::std::os::raw::c_uint,
            continuationStackSize: ::std::os::raw::c_uint,
            maxTraversableGraphDepth: ::std::os::raw::c_uint,
        ) -> OptixResult,
    >,
    pub optixAccelComputeMemoryUsage: ::std::option::Option<
        unsafe extern "C" fn(
            context: OptixDeviceContext,
            accelOptions: *const OptixAccelBuildOptions,
            buildInputs: *const OptixBuildInput,
            numBuildInputs: ::std::os::raw::c_uint,
            bufferSizes: *mut OptixAccelBufferSizes,
        ) -> OptixResult,
    >,
    pub optixAccelBuild: ::std::option::Option<
        unsafe extern "C" fn(
            context: OptixDeviceContext,
            stream: CUstream,
            accelOptions: *const OptixAccelBuildOptions,
            buildInputs: *const OptixBuildInput,
            numBuildInputs: ::std::os::raw::c_uint,
            tempBuffer: CUdeviceptr,
            tempBufferSizeInBytes: usize,
            outputBuffer: CUdeviceptr,
            outputBufferSizeInBytes: usize,
            outputHandle: *mut OptixTraversableHandle,
            emittedProperties: *const OptixAccelEmitDesc,
            numEmittedProperties: ::std::os::raw::c_uint,
        ) -> OptixResult,
    >,
    pub optixAccelGetRelocationInfo: ::std::option::Option<
        unsafe extern "C" fn(
            context: OptixDeviceContext,
            handle: OptixTraversableHandle,
            info: *mut OptixAccelRelocationInfo,
        ) -> OptixResult,
    >,
    pub optixAccelCheckRelocationCompatibility: ::std::option::Option<
        unsafe extern "C" fn(
            context: OptixDeviceContext,
            info: *const OptixAccelRelocationInfo,
            compatible: *mut ::std::os::raw::c_int,
        ) -> OptixResult,
    >,
    pub optixAccelRelocate: ::std::option::Option<
        unsafe extern "C" fn(
            context: OptixDeviceContext,
            stream: CUstream,
            info: *const OptixAccelRelocationInfo,
            instanceTraversableHandles: CUdeviceptr,
            numInstanceTraversableHandles: usize,
            targetAccel: CUdeviceptr,
            targetAccelSizeInBytes: usize,
            targetHandle: *mut OptixTraversableHandle,
        ) -> OptixResult,
    >,
    pub optixAccelCompact: ::std::option::Option<
        unsafe extern "C" fn(
            context: OptixDeviceContext,
            stream: CUstream,
            inputHandle: OptixTraversableHandle,
            outputBuffer: CUdeviceptr,
            outputBufferSizeInBytes: usize,
            outputHandle: *mut OptixTraversableHandle,
        ) -> OptixResult,
    >,
    pub optixConvertPointerToTraversableHandle: ::std::option::Option<
        unsafe extern "C" fn(
            onDevice: OptixDeviceContext,
            pointer: CUdeviceptr,
            traversableType: OptixTraversableType,
            traversableHandle: *mut OptixTraversableHandle,
        ) -> OptixResult,
    >,
    pub optixSbtRecordPackHeader: ::std::option::Option<
        unsafe extern "C" fn(
            programGroup: OptixProgramGroup,
            sbtRecordHeaderHostPointer: *mut ::std::os::raw::c_void,
        ) -> OptixResult,
    >,
    pub optixLaunch: ::std::option::Option<
        unsafe extern "C" fn(
            pipeline: OptixPipeline,
            stream: CUstream,
            pipelineParams: CUdeviceptr,
            pipelineParamsSize: usize,
            sbt: *const OptixShaderBindingTable,
            width: ::std::os::raw::c_uint,
            height: ::std::os::raw::c_uint,
            depth: ::std::os::raw::c_uint,
        ) -> OptixResult,
    >,
    pub optixDenoiserCreate: ::std::option::Option<
        unsafe extern "C" fn(
            context: OptixDeviceContext,
            options: *const OptixDenoiserOptions,
            returnHandle: *mut OptixDenoiser,
        ) -> OptixResult,
    >,
    pub optixDenoiserDestroy: ::std::option::Option<
        unsafe extern "C" fn(handle: OptixDenoiser) -> OptixResult,
    >,
    pub optixDenoiserComputeMemoryResources: ::std::option::Option<
        unsafe extern "C" fn(
            handle: OptixDenoiser,
            maximumOutputWidth: ::std::os::raw::c_uint,
            maximumOutputHeight: ::std::os::raw::c_uint,
            returnSizes: *mut OptixDenoiserSizes,
        ) -> OptixResult,
    >,
    pub optixDenoiserSetup: ::std::option::Option<
        unsafe extern "C" fn(
            denoiser: OptixDenoiser,
            stream: CUstream,
            outputWidth: ::std::os::raw::c_uint,
            outputHeight: ::std::os::raw::c_uint,
            state: CUdeviceptr,
            stateSizeInBytes: usize,
            scratch: CUdeviceptr,
            scratchSizeInBytes: usize,
        ) -> OptixResult,
    >,
    pub optixDenoiserInvoke: ::std::option::Option<
        unsafe extern "C" fn(
            denoiser: OptixDenoiser,
            stream: CUstream,
            params: *const OptixDenoiserParams,
            denoiserState: CUdeviceptr,
            denoiserStateSizeInBytes: usize,
            inputLayers: *const OptixImage2D,
            numInputLayers: ::std::os::raw::c_uint,
            inputOffsetX: ::std::os::raw::c_uint,
            inputOffsetY: ::std::os::raw::c_uint,
            outputLayer: *const OptixImage2D,
            scratch: CUdeviceptr,
            scratchSizeInBytes: usize,
        ) -> OptixResult,
    >,
    pub optixDenoiserSetModel: ::std::option::Option<
        unsafe extern "C" fn(
            handle: OptixDenoiser,
            kind: OptixDenoiserModelKind,
            data: *mut ::std::os::raw::c_void,
            sizeInBytes: usize,
        ) -> OptixResult,
    >,
    pub optixDenoiserComputeIntensity: ::std::option::Option<
        unsafe extern "C" fn(
            handle: OptixDenoiser,
            stream: CUstream,
            inputImage: *const OptixImage2D,
            outputIntensity: CUdeviceptr,
            scratch: CUdeviceptr,
            scratchSizeInBytes: usize,
        ) -> OptixResult,
    >,
}
pub const OptixSbtRecordHeaderSize: usize = 32;
pub const OptixSbtRecordAlignment: usize = 16;
pub const OptixAccelBufferByteAlignment: usize = 128;
pub const OptixInstanceByteAlignment: usize = 16;
pub const OptixAabbBufferByteAlignment: usize = 8;
pub const OptixGeometryTransformByteAlignment: usize = 16;
pub const OptixTransformByteAlignment: usize = 64;
#[repr(u32)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum OptixGeometryFlags {
    None = 0,
    DisableAnyHit = 1,
    RequireSingleAnyHitCall = 2,
}
